export default {
    GET_ALL_TASKS_START: 'GET_ALL_TASKS_START',
    GET_ALL_TASKS_SUCCESS: 'GET_ALL_TASKS_SUCCESS',
    GET_ALL_TASKS_FAILED: 'GET_ALL_TASKS_FAILED',
    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED'
}
